In [1]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

In [ ]:
# 1 - Carregue a base de dados, verifique os tipos de dados e também se há presença de dados faltantes ou nulos.

In [2]:
df = pd.read_csv("C:/Users/user/Documents/EBAC/dados/smoke_detection_iot.csv", delimiter=',')

df.head(10)

,Unnamed: 0,UTC,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5,CNT,Fire Alarm
0,0,1654733331,20.000,57.36,0,400,12306,18520,939.735,0.0,0.00,0.0,0.000,0.00,0,0
1,1,1654733332,20.015,56.67,0,400,12345,18651,939.744,0.0,0.00,0.0,0.000,0.00,1,0
2,2,1654733333,20.029,55.96,0,400,12374,18764,939.738,0.0,0.00,0.0,0.000,0.00,2,0
3,3,1654733334,20.044,55.28,0,400,12390,18849,939.736,0.0,0.00,0.0,0.000,0.00,3,0
4,4,1654733335,20.059,54.69,0,400,12403,18921,939.744,0.0,0.00,0.0,0.000,0.00,4,0
5,5,1654733336,20.073,54.12,0,400,12419,18998,939.725,0.0,0.00,0.0,0.000,0.00,5,0
6,6,1654733337,20.088,53.61,0,400,12432,19058,939.738,0.0,0.00,0.0,0.000,0.00,6,0
7,7,1654733338,20.103,53.20,0,400,12439,19114,939.758,0.0,0.00,0.0,0.000,0.00,7,0
8,8,1654733339,20.117,52.81,0,400,12448,19155,939.758,0.0,0.00,0.0,0.000,0.00,8,0
9,9,1654733340,20.132,52.46,0,400,12453,19195,939.756,0.9,3.78,0.0,4.369,2.78,9,0

In [5]:
df.isnull().values.any()

False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62630 entries, 0 to 62629
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      62630 non-null  int64
 1   UTC             62630 non-null  int64
 2   Temperature[C]  62630 non-null  float64
 3   Humidity[%]     62630 non-null  float64
 4   TVOC[ppb]       62630 non-null  int64
 5   eCO2[ppm]       62630 non-null  int64
 6   Raw H2          62630 non-null  int64
 7   Raw Ethanol     62630 non-null  int64
 8   Pressure[hPa]   62630 non-null  float64
 9   PM1.0           62630 non-null  float64
 10  PM2.5           62630 non-null  float64
 11  NC0.5           62630 non-null  float64
 12  NC1.0           62630 non-null  float64
 13  NC2.5           62630 non-null  float64
 14  CNT             62630 non-null  int64
 15  Fire Alarm      62630 non-null  int64
dtypes: float64(8), int64(8)
memory usage: 7.6 MB

In [7]:
df.rename(columns={'Fire Alarm': 'Fire_Alarm'}, inplace=True) # modificando o nome da coluna Fire Alarm para Fire_Alarm

In [8]:
df.head()

,Unnamed: 0,UTC,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5,CNT,Fire_Alarm
0,0,1654733331,20.000,57.36,0,400,12306,18520,939.735,0.0,0.0,0.0,0.0,0.0,0,0
1,1,1654733332,20.015,56.67,0,400,12345,18651,939.744,0.0,0.0,0.0,0.0,0.0,1,0
2,2,1654733333,20.029,55.96,0,400,12374,18764,939.738,0.0,0.0,0.0,0.0,0.0,2,0
3,3,1654733334,20.044,55.28,0,400,12390,18849,939.736,0.0,0.0,0.0,0.0,0.0,3,0
4,4,1654733335,20.059,54.69,0,400,12403,18921,939.744,0.0,0.0,0.0,0.0,0.0,4,0

In [9]:
# 2 - Para essa base, onde você realizará as previsões de fire alarm, qual modelo de machine learning você aplicará? Justifique.

In [10]:
# Utilizaremos regressão logística, para conseguir fazer a classificao binaria. Para uma variável binária, o objetivo é estimar a probabilidade de 
# ocorrência de um dos dois resultados (geralmente codificado como 1).

In [11]:
# 3 - Separe a base em Y e X e já rode a instância do modelo que você utilizará.

In [13]:
X = df.drop('Fire_Alarm', axis=1)
y = df['Fire_Alarm']

In [14]:
# Instanciando o modelo de regressão logística
modelo = LogisticRegression(max_iter=1000)

In [15]:
# 4 - Defina o número de Folds e rode o modelo com a validação cruzada.

In [16]:
folds = 5

In [17]:
crossvalidation = KFold(n_splits=folds, shuffle=True, random_state=5)

In [21]:
modelo_final = cross_val_score(modelo, X, y, cv = folds)

In [22]:
# 5 - Avalie a pontuação de cada modelo e ao final a validação final da média.

In [23]:
pontuacoes = cross_val_score(modelo, X, y, cv=crossvalidation)

print(f"Pontuações por fold: {pontuacoes}")

Pontuações por fold: [0.97620948 0.97573048 0.98842408 0.98626856 0.97684816]

In [25]:
#  Esta linha imprime as pontuações obtidas em cada uma das 5 divisões (folds). Cada valor representa a performance do modelo em um fold específico, 
# onde o modelo foi treinado com 4 dos 5 folds e testado no fold restante. Essas pontuações são obtidas através da métrica padrão usada pelo 
# cross_val_score, que geralmente é a acurácia para problemas de classificação.

In [ ]:
# Os valores de acurácia obtidos sao de aproximadamente 97,6% 97,5% 98,8% 98,62% e 97,6%

In [24]:
print((modelo_final.mean()))

0.9260737665655437